version: "3.5"

services:
  nginx:
    image: nginx:latest
    ports:
    - 127.0.0.1:81:80
    volumes:
    - ./www:/var/www/html
    - ./conf/nginx:/etc/nginx/conf.d
    - ./logs/nginx:/var/log/nginx
    links:
    - php-fpm

  php-fpm:
    build:
      context: php-fpm
    volumes:
    - ./www:/var/www/html
    links:
    - mariadb-srv

  mariadb-srv:
    image: mariadb:latest
    ports:
    - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testsite
      MYSQL_USER: user_test
      MYSQL_PASSWORD: userpass
    volumes:
    - ./databases/mariadb:/var/lib/mysql
      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - 127.0.0.1:8081:80
    environment:
      PMA_HOST: mariadb-srv
      PMA_USER: user_test
      PMA_PASSWORD: userpass